### ISSUE TITLE
PhotovoltaicDevice x-ngsi  model values sometimes with final dot, sometimes without

### ISSUE THREAD

**Issue by isalvadori** [smart-data-models/dataModel.GreenEnergy#4]
Hi, 
I noticed that in some cases the x-ngsi  model values in the https://github.com/smart-data-models/dataModel.GreenEnergy/blob/master/PhotovoltaicDevice/model.yaml have a final dot in the end, sometimes they do not.

```
MaximumSystemVoltage:
      x-ngsi:
        model: https://schema.org/Number
        type: Property
        units: Volt
```

```
 PanelNbModules:
      description: 'Number of ''Modules'' per ''Panel'''
      type: number
      x-ngsi:
        model: https://schema.org/Number.
```

Would it be possible to uniform a bit the style? In all the other models there is no dot in the end for such an attribute. 
It would be easy to extract the model information if the style would be the same for all the models and within the same model.

Thanks!
